[pygbag]
# アプリケーションの名前
title = SEXY!! 押忍リス
# アイコン (assets フォルダー内の画像を指定可能)
icon = assets/banana.png
# 解像度の設定
width = 800
height = 600
# 背景色 (HTML)
background_color = #222222

[DEPENDENCIES]
# pygbag 0.9.x が期待する必須項目をすべて網羅
assets = assets/
ignorefiles = .github,.vscode,.git,build,web-cache,doc
ignoredirs = .github,.vscode,.git,build,web-cache,doc
packages = 
